[package]
name = "adder"
version = "0.1.0"
authors = ["hiiragi-kaede <zoro18782ryt131@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

add-one = {path = "../add-one"}
rand = "0.3.14"